import { Task, TaskStatus, AgentFile } from "@/hooks/useEvodaoAgent";
import JSZip from "jszip";

export function buildMarkdown(
  goal: string,
  tasks: Task[],
  taskOutputs: Record<number, string>,
  taskStatuses: Record<number, TaskStatus>
): string {
  const lines: string[] = [];
  const now = new Date().toLocaleString();

  lines.push(`# ${goal}`);
  lines.push(`> Generated by EvoDao · ${now}`);
  lines.push("");

  tasks.forEach((task) => {
    const status = taskStatuses[task.id];
    const badge = status === "completed" ? "✓" : "✗";
    lines.push(`## [${badge}] Task ${task.id}: ${task.title}`);
    lines.push("");
    if (task.description) {
      lines.push(`_${task.description}_`);
      lines.push("");
    }
    const output = taskOutputs[task.id]?.trim();
    if (output) {
      lines.push(output);
      lines.push("");
    }
  });

  return lines.join("\n");
}

export function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  downloadBlob(blob, filename);
}

export function slugify(text: string, maxLen = 40): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .substring(0, maxLen);
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function downloadZip(files: AgentFile[], goalSlug: string) {
  const zip = new JSZip();
  files.forEach((f) => zip.file(f.path, f.content));
  const blob = await zip.generateAsync({ type: "blob" });
  downloadBlob(blob, `evodao-${goalSlug}.zip`);
}
